:sparkles: Add sample trigger and action
ifthen-gg/ifthen.gg pull request #24
Opened 2021-05-16 12:25 UTC by lmachens

2021-05-26 21:31 UTC, phlgr requested changes
Will look into it further tomorrow 😄

2021-05-26 21:31 UTC, phlgr commented on src/triggers/leagueQueue.test.ts
> +  it("clean up after event lisenter is removed", () => {
```suggestion
  it("cleans up after event listener is removed", () => {
```

2021-05-26 21:31 UTC, phlgr commented on src/triggers/triggerTarget.ts
> +  dispatches: {},
Either `listens` and `dispatches` or `listeners` and `dispatchers`

2021-05-26 21:31 UTC, phlgr commented on src/triggers/triggerTarget.ts
> +    }
```suggestion
    stack.forEach((listener: (arg: typeof data) => void) => {
      listener.call(this, data);
    });
```

2021-05-27 06:54 UTC, lmachens commented on src/triggers/triggerTarget.ts
> +    }
🤦‍♂️I shouldn't just copy & paste this example:
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget#simple_implementation_of_eventtarget

2021-05-31 12:26 UTC, phlgr approved these changes

2021-05-31 14:36 UTC, merged